'use client';

/**
 * Branded document templates — every PDF/CSV download in the suite renders
 * through these templates so output carries the active company's identity:
 * logo, legal name, registration numbers, address, currency and branding.
 *
 * PDFs are produced via a print-ready A4 document opened in a new window
 * (browser "Save as PDF" gives pixel-perfect output without heavy deps).
 */

import type { Workspace, Invoice, InvoiceLine, Bill, BillLine } from './data';
import { PAYMENT_METHOD_LABEL, fmtNum, CURRENCY_SYMBOL } from './data';

const esc = (s: string) =>
  String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const money = (ws: Workspace | null | undefined, n: number) => {
  const symbol = CURRENCY_SYMBOL[ws?.currency ?? 'USD'];
  return `${n < 0 ? '−' : ''}${symbol}${fmtNum(Math.abs(n))}`;
};

function logoBlock(ws: Workspace, size = 56): string {
  if (ws.logoDataUrl) {
    return `<img src="${ws.logoDataUrl}" alt="${esc(ws.name)} logo" style="height:${size}px;max-width:180px;object-fit:contain;" />`;
  }
  const initials = ws.name.slice(0, 2).toUpperCase();
  return `<div style="height:${size}px;width:${size}px;border-radius:14px;background:${ws.color};color:#fff;display:flex;align-items:center;justify-content:center;font-size:${size / 2.4}px;font-weight:700;letter-spacing:1px;">${initials}</div>`;
}

function companyBlock(ws: Workspace): string {
  const lines = [
    ws.legalName || ws.name,
    ws.addressLine ?? '',
    [ws.city, ws.state, ws.country].filter(Boolean).join(', '),
    [ws.businessNumber && `BN ${ws.businessNumber}`, ws.taxNumber && `Tax ${ws.taxNumber}`].filter(Boolean).join(' — '),
    [ws.email, ws.phone, ws.website].filter(Boolean).join('  —  '),
  ].filter(Boolean);
  return `<div style="font-size:11px;line-height:1.7;color:#555;">${lines.map((l) => `<div>${esc(l)}</div>`).join('')}</div>`;
}

const BASE_CSS = `
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; color: #1a1a1a; padding: 40px 48px; }
  .doc-header { display: flex; justify-content: space-between; align-items: flex-start; gap: 24px; border-bottom: 3px solid ${'#111'}; padding-bottom: 18px; margin-bottom: 8px; }
  .doc-title { font-size: 26px; font-weight: 700; letter-spacing: -0.5px; }
  .doc-sub { font-size: 12px; color: #666; margin-top: 4px; }
  .meta { font-size: 11px; color: #555; text-align: right; line-height: 1.7; }
  .section-title { font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 1.2px; color: #888; margin: 26px 0 8px; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; }
  th { text-align: left; padding: 8px 10px; background: #f4f4f5; border-bottom: 2px solid #e4e4e7; font-size: 10px; text-transform: uppercase; letter-spacing: 0.8px; color: #555; }
  td { padding: 8px 10px; border-bottom: 1px solid #eee; }
  .num { text-align: right; font-variant-numeric: tabular-nums; font-family: 'Consolas', monospace; font-size: 11.5px; }
  .total-row td { font-weight: 700; border-top: 2px solid #111; border-bottom: none; padding-top: 10px; }
  .grand td { font-size: 14px; font-weight: 700; border-top: 3px solid #111; }
  .footer { margin-top: 42px; padding-top: 12px; border-top: 1px solid #ddd; font-size: 10px; color: #999; display: flex; justify-content: space-between; }
  .badge { display: inline-block; padding: 3px 10px; border-radius: 999px; font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.8px; }
  .notes { margin-top: 18px; font-size: 11px; color: #444; background: #f8f8f8; border-radius: 8px; padding: 12px 14px; }
  @page { size: A4; margin: 0; }
  @media print { body { padding: 28px 36px; } }
`;

export function brandedDocHtml(opts: {
  ws: Workspace;
  title: string;
  subtitle?: string;
  metaRight?: string[];
  bodyHtml: string;
  footerNote?: string;
}): string {
  const { ws, title, subtitle, metaRight, bodyHtml, footerNote } = opts;
  return `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>${esc(title)} — ${esc(ws.name)}</title>
<style>${BASE_CSS}</style>
</head>
<body>
  <div class="doc-header">
    <div style="display:flex;gap:16px;align-items:center;">
      ${logoBlock(ws)}
      <div>
        <div class="doc-title">${esc(title)}</div>
        <div class="doc-sub">${esc(subtitle ?? '')}</div>
      </div>
    </div>
    <div style="text-align:right;">
      <div style="font-size:14px;font-weight:700;">${esc(ws.legalName || ws.name)}</div>
      <div class="meta">${companyBlock(ws)}</div>
      ${(metaRight ?? []).length ? `<div class="meta" style="margin-top:8px;">${(metaRight ?? []).map((m) => `<div>${esc(m ?? '')}</div>`).join('')}</div>` : ''}
    </div>
  </div>
  ${bodyHtml}
  <div class="footer">
    <span>${esc(footerNote ?? `Generated by Borga Company OS for ${ws.name}`)}</span>
    <span>Generated ${new Date().toLocaleString()}</span>
  </div>
</body>
</html>`;
}

export function openPrintWindow(html: string, title: string): void {
  const win = window.open('', '_blank', 'width=900,height=1000');
  if (!win) return;
  win.document.open();
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => {
    win.print();
  }, 350);
}

/** Prepend a branded company block to any CSV export. */
export function csvWithHeader(
  ws: Workspace,
  docTitle: string,
  periodLabel: string,
  rows: string[][],
): string {
  const q = (v: string) => `"${String(v).replace(/"/g, '""')}"`;
  const head: string[][] = [
    [ws.legalName || ws.name],
    [docTitle],
    [periodLabel],
    [
      [ws.addressLine ?? '', ws.city ?? '', ws.state ?? '', ws.country ?? ''].filter(Boolean).join(', '),
    ],
    [
      [ws.businessNumber && `Business No: ${ws.businessNumber}`, ws.taxNumber && `Tax No: ${ws.taxNumber}`]
        .filter(Boolean).join('  |  '),
    ],
    [[ws.email ?? '', ws.website ?? ''].filter(Boolean).join('  |  ')],
    [`Generated ${new Date().toLocaleString()}`],
    [],
  ];
  const body = rows.map((r) => r.map(q).join(','));
  return [...head.map((r) => r.map(q).join(',')), ...body].join('\n');
}

export function downloadTextFile(filename: string, content: string, mime = 'text/csv'): void {
  const blob = new Blob([content], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

// ── Invoice template ────────────────────────────────────────────────────────

export function invoiceHtml(inv: Invoice, ws: Workspace): string {
  const lines: InvoiceLine[] = inv.lines ?? [
    { id: 'l0', description: 'Services rendered', qty: 1, unitPrice: inv.amount },
  ];
  const subtotal = lines.reduce((s, l) => s + l.qty * l.unitPrice, 0);
  const taxRate = inv.taxRate ?? 0;
  const tax = (subtotal * taxRate) / 100;
  const total = subtotal + tax;
  const taxLabel = inv.taxProfileName ? `Tax (${inv.taxProfileName} ${taxRate}%)` : `Tax (${taxRate}%)`;

  const billTo = esc(inv.client);
  const statusBadge =
    inv.status === 'paid'
      ? '<span class="badge" style="background:#dcfce7;color:#15803d;">Paid</span>'
      : inv.status === 'overdue'
        ? '<span class="badge" style="background:#fee2e2;color:#b91c1c;">Overdue</span>'
        : inv.status === 'sent'
          ? '<span class="badge" style="background:#e0f2fe;color:#0369a1;">Sent</span>'
          : '<span class="badge" style="background:#f4f4f5;color:#52525b;">Draft</span>';

  const bodyHtml = `
  <div style="display:flex;justify-content:space-between;margin-top:22px;">
    <div>
      <div class="section-title">Bill to</div>
      <div style="font-size:14px;font-weight:700;">${billTo}</div>
    </div>
    <div style="text-align:right;">
      ${statusBadge}
      <div class="meta" style="margin-top:10px;">
        <div><strong>Invoice:</strong> ${esc(inv.number)}</div>
        <div><strong>Issued:</strong> ${esc(inv.issued)}</div>
        <div><strong>Due:</strong> ${esc(inv.due)}</div>
        ${inv.paymentMethod ? `<div><strong>Payment method:</strong> ${esc(PAYMENT_METHOD_LABEL[inv.paymentMethod])}</div>` : ''}
        ${inv.paidAt ? `<div><strong>Paid:</strong> ${esc(new Date(inv.paidAt).toLocaleString())} — ${inv.paidMethod ? esc(PAYMENT_METHOD_LABEL[inv.paidMethod]) : ''}</div>` : ''}
      </div>
    </div>
  </div>
  <div class="section-title">Items</div>
  <table>
    <thead><tr><th>Description</th><th class="num">Qty</th><th class="num">Unit price</th><th class="num">Amount</th></tr></thead>
    <tbody>
       ${lines.map((l) => `
         <tr>
           <td>${esc(l.description)}</td>
           <td class="num">${l.qty}</td>
           <td class="num">${money(ws, l.unitPrice)}</td>
           <td class="num">${money(ws, l.qty * l.unitPrice)}</td>
         </tr>`).join('')}
       <tr><td colspan="3" class="num">Subtotal</td><td class="num">${money(ws, subtotal)}</td></tr>
       ${taxRate > 0 ? `<tr><td colspan="3" class="num">${taxLabel}</td><td class="num">${money(ws, tax)}</td></tr>` : ''}
       <tr class="grand"><td colspan="3" class="num">Total due (${ws.currency})</td><td class="num">${money(ws, total)}</td></tr>
     </tbody>
   </table>
   ${inv.notes ? `<div class="notes"><strong>Notes:</strong> ${esc(inv.notes)}</div>` : ''}
  <div class="notes"><strong>Payment:</strong> Please settle via ${esc(inv.paymentMethod ? PAYMENT_METHOD_LABEL[inv.paymentMethod] : 'bank transfer')}, quoting invoice ${esc(inv.number)}.
  ${ws.businessNumber ? ` &nbsp;—&nbsp; ${esc(ws.businessNumber)}` : ''}${ws.taxNumber ? ` &nbsp;—&nbsp; Tax ${esc(ws.taxNumber)}` : ''}</div>`;

  return brandedDocHtml({
    ws,
    title: 'INVOICE',
    subtitle: `${ws.tradingName || ws.name} — ${ws.industry ?? ''}`,
    bodyHtml,
    footerNote: `Thank you for your business — ${ws.name}`,
  });
}

export function billHtml(
  bill: Bill,
  ws: Workspace,
): string {
  const lines: BillLine[] = bill.lines ?? [
    { id: 'l0', description: 'Services / goods received', qty: 1, unitPrice: bill.amount },
  ];
  const subtotal = lines.reduce((s, l) => s + l.qty * l.unitPrice, 0);
  const taxRate = bill.taxRate ?? 0;
  const tax = (subtotal * taxRate) / 100;
  const total = subtotal + tax;
  const taxLabel = bill.taxProfileName ? `Tax (${bill.taxProfileName} ${taxRate}%)` : `Tax (${taxRate}%)`;

  const statusBadge =
    bill.status === 'paid'
      ? '<span class="badge" style="background:#dcfce7;color:#15803d;">Paid</span>'
      : bill.status === 'scheduled'
        ? '<span class="badge" style="background:#e0f2fe;color:#0369a1;">Scheduled</span>'
        : '<span class="badge" style="background:#fef3c7;color:#b45309;">Unpaid</span>';

  const bodyHtml = `
  <div style="display:flex;justify-content:space-between;margin-top:22px;">
    <div>
      <div class="section-title">Pay to</div>
      <div style="font-size:14px;font-weight:700;">${esc(bill.vendorName)}</div>
    </div>
    <div style="text-align:right;">
      ${statusBadge}
      <div class="meta" style="margin-top:10px;">
        <div><strong>Bill:</strong> ${esc(bill.number)}</div>
        <div><strong>Received:</strong> ${esc(bill.received)}</div>
        <div><strong>Due:</strong> ${esc(bill.due)}</div>
        ${bill.paymentMethod ? `<div><strong>Payment method:</strong> ${esc(PAYMENT_METHOD_LABEL[bill.paymentMethod])}</div>` : ''}
        ${bill.paidAt ? `<div><strong>Paid:</strong> ${esc(new Date(bill.paidAt).toLocaleString())} — ${bill.paidMethod ? esc(PAYMENT_METHOD_LABEL[bill.paidMethod]) : ''}</div>` : ''}
      </div>
    </div>
  </div>
  <div class="section-title">Items</div>
  <table>
    <thead><tr><th>Description</th><th class="num">Qty</th><th class="num">Unit price</th><th class="num">Amount</th></tr></thead>
    <tbody>
       ${lines.map((l) => `
         <tr>
           <td>${esc(l.description)}</td>
           <td class="num">${l.qty}</td>
           <td class="num">${money(ws, l.unitPrice)}</td>
           <td class="num">${money(ws, l.qty * l.unitPrice)}</td>
         </tr>`).join('')}
       <tr><td colspan="3" class="num">Subtotal</td><td class="num">${money(ws, subtotal)}</td></tr>
       ${taxRate > 0 ? `<tr><td colspan="3" class="num">${taxLabel}</td><td class="num">${money(ws, tax)}</td></tr>` : ''}
       <tr class="grand"><td colspan="3" class="num">Total due (${ws.currency})</td><td class="num">${money(ws, total)}</td></tr>
     </tbody>
   </table>
   ${bill.notes ? `<div class="notes"><strong>Notes:</strong> ${esc(bill.notes)}</div>` : ''}
  <div class="notes"><strong>Payment:</strong> Please settle via ${esc(bill.paymentMethod ? PAYMENT_METHOD_LABEL[bill.paymentMethod] : 'bank transfer')}, quoting bill ${esc(bill.number)}.
  ${ws.businessNumber ? ` &nbsp;—&nbsp; ${esc(ws.businessNumber)}` : ''}${ws.taxNumber ? ` &nbsp;—&nbsp; Tax ${esc(ws.taxNumber)}` : ''}</div>`;

  return brandedDocHtml({
    ws,
    title: 'BILL',
    subtitle: `Accounts payable — ${ws.name}`,
    bodyHtml,
    footerNote: `Thank you — ${ws.name}`,
  });
}
